# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :aws do |aws, override|
    aws.keypair_name = "ec2_key"
    aws.access_key_id = ENV['AWS_ACCESS_KEY']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    # aws.instance_type = "t1.micro"
    aws.security_groups = ["vagrant"]
    aws.ami = "ami-a73264ce"
    override.ssh.private_key_path = ENV['AWS_PRIVATE_KEY']
    override.ssh.username = "ubuntu"
    # aws.tags = { 'Name' => 'ec2-vagracluster', }
  end
end